/*
 * Problem Statement:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * https://projecteuler.net/problem=2
 */

import java.util.Scanner;

public class EvenFibonacciNumbers {

	public static void main(String[] args) {
		/*
		 * Read
		 */
		//Declare variables
		Scanner scan = new Scanner(System.in);
		String input = "";
		int termNums = 0;
		int isEven = 1;
		int currentFib = 1;
		int previousFib = 0;
		int temp;
		int limit = 0;
		int sum = 0;
		
		//Get the number of terms
		System.out.println("How many terms should there be? ");
		termNums = scan.nextInt();
		
		//Get the even or odd numbers
		while(true){
			System.out.println("Do you want to sum the even or odd numbers? ");
			input = scan.next();
			if(input.equalsIgnoreCase("even") ){
				isEven = 1;
				break;
			}else if(input.equalsIgnoreCase("odd") ){
				isEven = 0;
				sum = 1;
				break;
			}else{
				System.out.println("That is not an acceptable answer.");
			}
		}
	
		//Get term value limits
		System.out.println("What should be the maximum fibonacci value? ");
		limit = scan.nextInt();
		
		/*
		 * Think		
		 */
		//Go through all Fibonacci numbers and add together the even or odd numbers
		for(int i = 1; i<termNums; i++){
			temp = currentFib;
			currentFib = currentFib + previousFib;
			previousFib = temp;
			System.out.print(currentFib);
			//Break out of loop if the current fibonacci number exceeds the limit
			if(currentFib > limit){
				break;
			}
			if(isEven==1){
				//Check if even
				if(currentFib%2 == 0){
					sum = sum + currentFib;
					System.out.print(": Even");
				}
			}else{
				//Check if odd
				if(currentFib%2 != 0){
					sum = sum + currentFib;
					System.out.print(": Odd");
				}
			}
			System.out.println();
		}
		
		/*
		 * Do
		 */
		//Output the sum
		System.out.println("The sum is: " + sum);
		scan.close();
		
	}

}
